 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container marcelo-python-async-db-1  Creating
 Container marcelo-python-async-db-1  Created
 Container marcelo-python-async-api01-1  Creating
 Container marcelo-python-async-api01-1  Created
 Container marcelo-python-async-api02-1  Creating
 Container marcelo-python-async-api02-1  Created
 Container marcelo-python-async-load_balancer-1  Creating
 Container marcelo-python-async-load_balancer-1  Created
Attaching to api01-1, api02-1, db-1, load_balancer-1
db-1             | The files belonging to this database system will be owned by user "postgres".
db-1             | This user must also own the server process.
db-1             | 
db-1             | The database cluster will be initialized with locale "en_US.utf8".
db-1             | The default database encoding has accordingly been set to "UTF8".
db-1             | The default text search configuration will be set to "english".
db-1             | 
db-1             | Data page checksums are disabled.
db-1             | 
db-1             | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1             | creating subdirectories ... ok
db-1             | selecting dynamic shared memory implementation ... posix
db-1             | selecting default max_connections ... 100
db-1             | selecting default shared_buffers ... 128MB
db-1             | selecting default time zone ... Etc/UTC
db-1             | creating configuration files ... ok
db-1             | running bootstrap script ... ok
db-1             | performing post-bootstrap initialization ... ok
db-1             | syncing data to disk ... ok
db-1             | 
db-1             | 
db-1             | Success. You can now start the database server using:
db-1             | 
db-1             |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1             | 
db-1             | initdb: warning: enabling "trust" authentication for local connections
db-1             | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1             | waiting for server to start....2024-03-10 17:21:58.516 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db-1             | 2024-03-10 17:21:58.516 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-03-10 17:21:58.518 UTC [51] LOG:  database system was shut down at 2024-03-10 17:21:57 UTC
db-1             | 2024-03-10 17:21:58.521 UTC [48] LOG:  database system is ready to accept connections
db-1             |  done
db-1             | server started
db-1             | CREATE DATABASE
db-1             | 
db-1             | 
db-1             | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_db.sql
db-1             | SET
db-1             | DROP TABLE
db-1             | psql:/docker-entrypoint-initdb.d/create_db.sql:3: NOTICE:  table "cliente" does not exist, skipping
db-1             | DROP TABLE
db-1             | psql:/docker-entrypoint-initdb.d/create_db.sql:5: NOTICE:  table "transacao" does not exist, skipping
db-1             | CREATE TABLE
db-1             | CREATE TABLE
db-1             | CREATE INDEX
db-1             | CREATE INDEX
db-1             | CREATE INDEX
db-1             | INSERT 0 5
db-1             | CREATE FUNCTION
db-1             | CREATE FUNCTION
db-1             | CREATE FUNCTION
db-1             | 
db-1             | 
db-1             | 2024-03-10 17:21:58.721 UTC [48] LOG:  received fast shutdown request
db-1             | 2024-03-10 17:21:58.721 UTC [48] LOG:  aborting any active transactions
db-1             | 2024-03-10 17:21:58.722 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1             | waiting for server to shut down....2024-03-10 17:21:58.724 UTC [49] LOG:  shutting down
db-1             | 2024-03-10 17:21:58.724 UTC [49] LOG:  checkpoint starting: shutdown immediate
load_balancer-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
load_balancer-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
load_balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db-1             | 2024-03-10 17:21:58.732 UTC [49] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.001 s, total=0.009 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4296 kB, estimate=4296 kB; lsn=0/1919390, redo lsn=0/1919390
db-1             | 2024-03-10 17:21:58.736 UTC [48] LOG:  database system is shut down
load_balancer-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
load_balancer-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
load_balancer-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
load_balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
load_balancer-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
load_balancer-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1             |  done
db-1             | server stopped
db-1             | 
db-1             | PostgreSQL init process complete; ready for start up.
db-1             | 
db-1             | 2024-03-10 17:21:58.837 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db-1             | 2024-03-10 17:21:58.837 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1             | 2024-03-10 17:21:58.837 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1             | 2024-03-10 17:21:58.837 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-03-10 17:21:58.839 UTC [66] LOG:  database system was shut down at 2024-03-10 17:21:58 UTC
db-1             | 2024-03-10 17:21:58.841 UTC [1] LOG:  database system is ready to accept connections
load_balancer-1  | 2024/03/10 17:22:00 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:00 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.4:8082/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:02 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:02 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.4:8082/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:04 [error] 32#32: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:04 [error] 32#32: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.4:8082/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:06 [error] 31#31: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:06 [error] 31#31: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.26.0.4:8082/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:08 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:10 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:17 [error] 31#31: *30 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:17 [error] 31#31: *31 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:17 [error] 31#31: *32 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:17 [error] 32#32: *25 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:21 [error] 32#32: *126 upstream prematurely closed connection while reading response header from upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://172.26.0.4:8082/clientes/4/transacoes", host: "localhost:9999"
api02-1          | Traceback (most recent call last):
api02-1          |   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
api02-1          |   File "/api/Server/request_handler.py", line 25, in handle_client
api02-1          |     status_code, response = self.process_request(req.parsed_request)
api02-1          |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api02-1          |   File "/api/Server/request_handler.py", line 53, in process_request
api02-1          |     return self.controller.post_transaction(
api02-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api02-1          |   File "/api/Controllers/controller.py", line 58, in post_transaction
api02-1          |     if not transaction.is_invalid() and not client.is_invalid():
api02-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^
api02-1          |   File "/api/Models/transaction.py", line 47, in is_invalid
api02-1          |     or len(self.descricao) > 10
api02-1          |        ^^^^^^^^^^^^^^^^^^^
api02-1          | TypeError: object of type 'NoneType' has no len()
api02-1          | 2024-03-10T17:22:21Z <Greenlet at 0x7f04461a60c0: <bound method RequestHandler.handle_client of <Server.request_handler.RequestHandler object at 0x7f0443a1a5d0>>(<Models.tcp_request.TcpRequest object at 0x7f0443a)> failed with TypeError
api02-1          | 
api01-1          | Traceback (most recent call last):
load_balancer-1  | 2024/03/10 17:22:21 [error] 32#32: *129 upstream prematurely closed connection while reading response header from upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/2/transacoes", host: "localhost:9999"
api01-1          |   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
api01-1          |   File "/api/Server/request_handler.py", line 25, in handle_client
api01-1          |     status_code, response = self.process_request(req.parsed_request)
api01-1          |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Server/request_handler.py", line 53, in process_request
api01-1          |     return self.controller.post_transaction(
api01-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Controllers/controller.py", line 58, in post_transaction
api01-1          |     if not transaction.is_invalid() and not client.is_invalid():
api01-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Models/transaction.py", line 47, in is_invalid
api01-1          |     or len(self.descricao) > 10
api01-1          |        ^^^^^^^^^^^^^^^^^^^
api01-1          | TypeError: object of type 'NoneType' has no len()
api01-1          | 2024-03-10T17:22:21Z <Greenlet at 0x7f86929b60c0: <bound method RequestHandler.handle_client of <Server.request_handler.RequestHandler object at 0x7f86928e9c50>>(<Models.tcp_request.TcpRequest object at 0x7f86902)> failed with TypeError
api01-1          | 
load_balancer-1  | 2024/03/10 17:22:21 [error] 31#31: *122 upstream prematurely closed connection while reading response header from upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://172.26.0.3:8081/clientes/3/transacoes", host: "localhost:9999"
api01-1          | Traceback (most recent call last):
api01-1          |   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
api01-1          |   File "/api/Server/request_handler.py", line 25, in handle_client
api01-1          |     status_code, response = self.process_request(req.parsed_request)
api01-1          |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Server/request_handler.py", line 53, in process_request
api01-1          |     return self.controller.post_transaction(
api01-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Controllers/controller.py", line 58, in post_transaction
api01-1          |     if not transaction.is_invalid() and not client.is_invalid():
api01-1          |            ^^^^^^^^^^^^^^^^^^^^^^^^
api01-1          |   File "/api/Models/transaction.py", line 47, in is_invalid
api01-1          |     or len(self.descricao) > 10
api01-1          |        ^^^^^^^^^^^^^^^^^^^
api01-1          | TypeError: object of type 'NoneType' has no len()
api01-1          | 2024-03-10T17:22:21Z <Greenlet at 0x7f86929b60c0: <bound method RequestHandler.handle_client of <Server.request_handler.RequestHandler object at 0x7f86928e9c50>>(<Models.tcp_request.TcpRequest object at 0x7f86902)> failed with TypeError
api01-1          | 
load_balancer-1  | 2024/03/10 17:22:21 [error] 32#32: *125 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:21 [error] 32#32: *121 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *247 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *248 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *249 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *250 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *251 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://api/clientes/3/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *252 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://api/clientes/4/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *253 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *254 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *255 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *256 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:25 [error] 32#32: *257 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:26 [error] 32#32: *258 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:26 [error] 32#32: *259 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:26 [error] 32#32: *260 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:26 [error] 32#32: *261 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/3/extrato HTTP/1.1", upstream: "http://api/clientes/3/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:26 [error] 32#32: *262 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *359 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *360 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *361 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://api/clientes/4/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *362 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *363 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *364 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *365 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *366 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://api/clientes/4/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *367 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *368 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://api/clientes/4/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *369 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *370 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/4/transacoes HTTP/1.1", upstream: "http://api/clientes/4/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *371 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *372 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *373 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:29 [error] 32#32: *374 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *471 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *472 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/2/transacoes HTTP/1.1", upstream: "http://api/clientes/2/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *473 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *474 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *475 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *476 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *477 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/3/transacoes HTTP/1.1", upstream: "http://api/clientes/3/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *478 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *479 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *480 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/1/transacoes HTTP/1.1", upstream: "http://api/clientes/1/transacoes", host: "localhost:9999"
load_balancer-1  | 2024/03/10 17:22:31 [error] 32#32: *481 no live upstreams while connecting to upstream, client: 172.26.0.1, server: , request: "POST /clientes/5/transacoes HTTP/1.1", upstream: "http://api/clientes/5/transacoes", host: "localhost:9999"
load_balancer-1 exited with code 0
load_balancer-1 exited with code 0
api02-1 exited with code 0
api02-1 exited with code 137
api01-1 exited with code 0
api01-1 exited with code 137
db-1             | 2024-03-10 17:26:46.823 UTC [1] LOG:  received fast shutdown request
db-1             | 2024-03-10 17:26:46.823 UTC [1] LOG:  aborting any active transactions
db-1             | 2024-03-10 17:26:46.824 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1             | 2024-03-10 17:26:46.824 UTC [64] LOG:  shutting down
db-1             | 2024-03-10 17:26:46.825 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1             | 2024-03-10 17:26:46.829 UTC [64] LOG:  checkpoint complete: wrote 1013 buffers (6.2%); 0 WAL file(s) added, 0 removed, 2 recycled; write=0.005 s, sync=0.001 s, total=0.005 s; sync files=0, longest=0.000 s, average=0.000 s; distance=24525 kB, estimate=24525 kB; lsn=0/310CA30, redo lsn=0/310CA30
db-1             | 2024-03-10 17:26:46.833 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
