 Container rinha-db  Creating
 Container rinha-db  Created
 Container rinha-api-02  Creating
 Container rinha-api-01  Creating
 Container rinha-api-02  Created
 Container rinha-api-01  Created
 Container nginx-rinha-2024  Creating
 Container nginx-rinha-2024  Created
Attaching to nginx-rinha-2024, rinha-api-01, rinha-api-02, rinha-db
rinha-db          | The files belonging to this database system will be owned by user "postgres".
rinha-db          | This user must also own the server process.
rinha-db          | 
rinha-db          | The database cluster will be initialized with locale "en_US.utf8".
rinha-db          | The default database encoding has accordingly been set to "UTF8".
rinha-db          | The default text search configuration will be set to "english".
rinha-db          | 
rinha-db          | Data page checksums are disabled.
rinha-db          | 
rinha-db          | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinha-db          | creating subdirectories ... ok
rinha-db          | selecting dynamic shared memory implementation ... posix
rinha-db          | selecting default max_connections ... 100
rinha-db          | selecting default shared_buffers ... 128MB
rinha-db          | selecting default time zone ... Etc/UTC
rinha-db          | creating configuration files ... ok
rinha-db          | running bootstrap script ... ok
nginx-rinha-2024  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-rinha-2024  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-rinha-2024  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-rinha-2024  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-rinha-2024  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-rinha-2024  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-rinha-2024  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-rinha-2024  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-rinha-2024  | /docker-entrypoint.sh: Configuration complete; ready for start up
rinha-api-02      | Traceback (most recent call last):
rinha-api-02      |   File "/app/app.py", line 3, in <module>
rinha-api-02      |     from src.routes import client_operations_blueprint
rinha-api-02      |   File "/app/src/routes.py", line 2, in <module>
rinha-api-02      |     from .controllers import make_transaction_controller, get_statement_controller
rinha-api-02      |   File "/app/src/controllers.py", line 3, in <module>
rinha-api-02      |     from .database import database_connection
rinha-api-02      |   File "/app/src/database.py", line 4, in <module>
rinha-api-02      |     database_connection = psycopg2.connect(
rinha-api-02      |                           ^^^^^^^^^^^^^^^^^
rinha-api-02      |   File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
rinha-api-02      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
rinha-api-01      | Traceback (most recent call last):
rinha-api-01      |   File "/app/app.py", line 3, in <module>
rinha-api-01      |     from src.routes import client_operations_blueprint
rinha-api-01      |   File "/app/src/routes.py", line 2, in <module>
rinha-api-01      |     from .controllers import make_transaction_controller, get_statement_controller
rinha-api-01      |   File "/app/src/controllers.py", line 3, in <module>
rinha-api-02      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api-02      | psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 12345 failed: Connection refused
rinha-api-02      | 	Is the server running on that host and accepting TCP/IP connections?
rinha-api-02      | 
rinha-api-01      |     from .database import database_connection
rinha-api-01      |   File "/app/src/database.py", line 4, in <module>
rinha-api-01      |     database_connection = psycopg2.connect(
rinha-api-01      |                           ^^^^^^^^^^^^^^^^^
rinha-api-01      |   File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
rinha-api-01      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
rinha-api-01      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api-01      | psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 12345 failed: Connection refused
rinha-api-01      | 	Is the server running on that host and accepting TCP/IP connections?
rinha-api-01      | 
rinha-db          | performing post-bootstrap initialization ... ok
rinha-api-02 exited with code 0
rinha-api-01 exited with code 0
rinha-db          | initdb: warning: enabling "trust" authentication for local connections
rinha-db          | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinha-db          | syncing data to disk ... ok
rinha-db          | 
rinha-db          | 
rinha-db          | Success. You can now start the database server using:
rinha-db          | 
rinha-db          |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinha-db          | 
rinha-db          | waiting for server to start....2024-02-24 22:02:53.714 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-db          | 2024-02-24 22:02:53.717 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.12345"
rinha-db          | 2024-02-24 22:02:53.727 UTC [51] LOG:  database system was shut down at 2024-02-24 22:02:53 UTC
rinha-db          | 2024-02-24 22:02:53.734 UTC [48] LOG:  database system is ready to accept connections
rinha-db          |  done
rinha-db          | server started
rinha-db          | CREATE DATABASE
rinha-db          | 
rinha-db          | 
rinha-db          | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
rinha-db          | CREATE TABLE
rinha-db          | CREATE TABLE
rinha-db          | INSERT 0 5
rinha-db          | 
rinha-db          | 
rinha-db          | waiting for server to shut down...2024-02-24 22:02:54.028 UTC [48] LOG:  received fast shutdown request
rinha-db          | .2024-02-24 22:02:54.030 UTC [48] LOG:  aborting any active transactions
rinha-db          | 2024-02-24 22:02:54.033 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
rinha-db          | 2024-02-24 22:02:54.034 UTC [49] LOG:  shutting down
rinha-db          | 2024-02-24 22:02:54.036 UTC [49] LOG:  checkpoint starting: shutdown immediate
rinha-api-02      | Traceback (most recent call last):
rinha-api-02      |   File "/app/app.py", line 3, in <module>
rinha-api-02      |     from src.routes import client_operations_blueprint
rinha-api-02      |   File "/app/src/routes.py", line 2, in <module>
rinha-api-02      |     from .controllers import make_transaction_controller, get_statement_controller
rinha-api-02      |   File "/app/src/controllers.py", line 3, in <module>
rinha-api-02      |     from .database import database_connection
rinha-api-02      |   File "/app/src/database.py", line 4, in <module>
rinha-api-02      |     database_connection = psycopg2.connect(
rinha-api-02      |                           ^^^^^^^^^^^^^^^^^
rinha-api-02      |   File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
rinha-api-02      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
rinha-api-02      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api-02      | psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 12345 failed: Connection refused
rinha-api-02      | 	Is the server running on that host and accepting TCP/IP connections?
rinha-api-02      | 
rinha-api-01      | Traceback (most recent call last):
rinha-api-01      |   File "/app/app.py", line 3, in <module>
rinha-api-01      |     from src.routes import client_operations_blueprint
rinha-api-01      |   File "/app/src/routes.py", line 2, in <module>
rinha-api-01      |     from .controllers import make_transaction_controller, get_statement_controller
rinha-api-01      |   File "/app/src/controllers.py", line 3, in <module>
rinha-api-01      |     from .database import database_connection
rinha-api-01      |   File "/app/src/database.py", line 4, in <module>
rinha-api-01      |     database_connection = psycopg2.connect(
rinha-api-01      |                           ^^^^^^^^^^^^^^^^^
rinha-api-01      |   File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
rinha-api-01      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
rinha-api-01      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rinha-api-01      | psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 12345 failed: Connection refused
rinha-api-01      | 	Is the server running on that host and accepting TCP/IP connections?
rinha-api-01      | 
rinha-db          | .2024-02-24 22:02:55.317 UTC [49] LOG:  checkpoint complete: wrote 938 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.557 s, sync=0.715 s, total=1.284 s; sync files=307, longest=0.254 s, average=0.003 s; distance=4291 kB, estimate=4291 kB; lsn=0/191B758, redo lsn=0/191B758
rinha-db          | 2024-02-24 22:02:55.323 UTC [48] LOG:  database system is shut down
rinha-api-02 exited with code 0
rinha-db          |  done
rinha-db          | server stopped
rinha-db          | 
rinha-db          | PostgreSQL init process complete; ready for start up.
rinha-db          | 
rinha-db          | 2024-02-24 22:02:55.355 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-db          | 2024-02-24 22:02:55.355 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 12345
rinha-db          | 2024-02-24 22:02:55.355 UTC [1] LOG:  listening on IPv6 address "::", port 12345
rinha-db          | 2024-02-24 22:02:55.361 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.12345"
rinha-db          | 2024-02-24 22:02:55.368 UTC [66] LOG:  database system was shut down at 2024-02-24 22:02:55 UTC
rinha-db          | 2024-02-24 22:02:55.377 UTC [1] LOG:  database system is ready to accept connections
rinha-api-01 exited with code 0
rinha-api-02      |  * Serving Flask app 'app'
rinha-api-02      |  * Debug mode: off
rinha-api-01      |  * Serving Flask app 'app'
rinha-api-01      |  * Debug mode: off
nginx-rinha-2024 exited with code 0
nginx-rinha-2024 exited with code 0
rinha-db          | 2024-02-24 22:07:18.105 UTC [71] LOG:  unexpected EOF on client connection with an open transaction
rinha-db          | 2024-02-24 22:07:18.111 UTC [70] LOG:  unexpected EOF on client connection with an open transaction
rinha-api-01 exited with code 0
rinha-api-02 exited with code 0
rinha-api-02 exited with code 137
rinha-api-01 exited with code 137
rinha-db          | 2024-02-24 22:07:18.470 UTC [1] LOG:  received fast shutdown request
rinha-db          | 2024-02-24 22:07:18.474 UTC [1] LOG:  aborting any active transactions
rinha-db          | 2024-02-24 22:07:18.476 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
rinha-db          | 2024-02-24 22:07:18.476 UTC [64] LOG:  shutting down
rinha-db          | 2024-02-24 22:07:18.479 UTC [64] LOG:  checkpoint starting: shutdown immediate
rinha-db          | 2024-02-24 22:07:18.719 UTC [64] LOG:  checkpoint complete: wrote 608 buffers (3.7%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.015 s, sync=0.207 s, total=0.244 s; sync files=31, longest=0.171 s, average=0.007 s; distance=15506 kB, estimate=15506 kB; lsn=0/2840140, redo lsn=0/2840140
rinha-db          | 2024-02-24 22:07:18.723 UTC [1] LOG:  database system is shut down
rinha-db exited with code 0
