 Network lucianovilela_default  Creating
 Network lucianovilela_default  Created
 Container lucianovilela-db-1  Creating
 db Published ports are discarded when using host network mode 
 Container lucianovilela-db-1  Created
 Container lucianovilela-api02-1  Creating
 Container lucianovilela-api01-1  Creating
 api01 Published ports are discarded when using host network mode 
 Container lucianovilela-api01-1  Created
 api02 Published ports are discarded when using host network mode 
 Container lucianovilela-api02-1  Created
 Container lucianovilela-nginx-1  Creating
 Container lucianovilela-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
api01-1  | Servidor rodando na porta 9000
api02-1  | Servidor rodando na porta 9001
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | running bootstrap script ... ok
nginx-1  | 2024/02/14 19:52:13 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:13 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:13 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:13 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-14 19:52:13.796 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-14 19:52:13.798 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-14 19:52:13.807 UTC [51] LOG:  database system was shut down at 2024-02-14 19:52:13 UTC
db-1     | 2024-02-14 19:52:13.865 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-14 19:52:14.666 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-02-14 19:52:14.692 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-14 19:52:14.695 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-14 19:52:14.695 UTC [49] LOG:  shutting down
db-1     | 2024-02-14 19:52:14.711 UTC [49] LOG:  checkpoint starting: shutdown immediate
nginx-1  | 2024/02/14 19:52:15 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:15 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:15 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:15 [error] 30#30: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
db-1     | 2024-02-14 19:52:15.239 UTC [49] LOG:  checkpoint complete: wrote 944 buffers (5.8%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.411 s, sync=0.027 s, total=0.545 s; sync files=310, longest=0.004 s, average=0.001 s; distance=4313 kB, estimate=4313 kB; lsn=0/19211D8, redo lsn=0/19211D8
db-1     | 2024-02-14 19:52:15.249 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-14 19:52:15.312 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-14 19:52:15.312 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-14 19:52:15.312 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-14 19:52:15.318 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-14 19:52:15.328 UTC [66] LOG:  database system was shut down at 2024-02-14 19:52:15 UTC
db-1     | 2024-02-14 19:52:15.366 UTC [1] LOG:  database system is ready to accept connections
nginx-1  | 2024/02/14 19:52:17 [error] 32#32: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:17 [error] 32#32: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:17 [error] 32#32: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:17 [error] 32#32: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:19 [error] 31#31: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:19 [error] 31#31: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:19 [error] 31#31: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:19 [error] 31#31: *16 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:21 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:23 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:25 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:25 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:25 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:25 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:27 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:29 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:31 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:33 [error] 29#29: *31 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:35 [error] 29#29: *32 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:37 [error] 29#29: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:37 [error] 29#29: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:37 [error] 29#29: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:37 [error] 29#29: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:39 [error] 29#29: *38 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:41 [error] 29#29: *39 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:43 [error] 29#29: *40 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:45 [error] 29#29: *41 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:47 [error] 29#29: *42 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:49 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:49 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:49 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:49 [error] 29#29: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:9000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/14 19:52:51 [error] 29#29: *48 no live upstreams while connecting to upstream, client: 192.168.80.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
api01-1 exited with code 0
api01-1 exited with code 137
api02-1 exited with code 0
api02-1 exited with code 137
db-1     | 2024-02-14 19:53:05.063 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-14 19:53:05.065 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-14 19:53:05.068 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-14 19:53:05.069 UTC [64] LOG:  shutting down
db-1     | 2024-02-14 19:53:05.071 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-14 19:53:05.091 UTC [64] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.006 s, total=0.023 s; sync files=13, longest=0.004 s, average=0.001 s; distance=238 kB, estimate=238 kB; lsn=0/195CD70, redo lsn=0/195CD70
db-1     | 2024-02-14 19:53:05.098 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
