 Network gabrielbarbieri-nodejs_default  Creating
 Network gabrielbarbieri-nodejs_default  Created
 Container mypostgres  Creating
 Container mypostgres  Created
 Container api1  Creating
 Container api2  Creating
 Container api1  Created
 Container api2  Created
 Container mynginx  Creating
 Container mynginx  Created
Attaching to api1, api2, mynginx, mypostgres
mypostgres  | The files belonging to this database system will be owned by user "postgres".
mypostgres  | This user must also own the server process.
mypostgres  | 
mypostgres  | The database cluster will be initialized with locale "en_US.utf8".
mypostgres  | The default database encoding has accordingly been set to "UTF8".
mypostgres  | The default text search configuration will be set to "english".
mypostgres  | 
mypostgres  | Data page checksums are disabled.
mypostgres  | 
mypostgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
mypostgres  | creating subdirectories ... ok
mypostgres  | selecting dynamic shared memory implementation ... posix
mypostgres  | selecting default max_connections ... 100
mypostgres  | selecting default shared_buffers ... 128MB
mypostgres  | selecting default time zone ... Etc/UTC
mypostgres  | creating configuration files ... ok
mypostgres  | running bootstrap script ... ok
mypostgres  | performing post-bootstrap initialization ... ok
mypostgres  | initdb: warning: enabling "trust" authentication for local connections
mypostgres  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
mypostgres  | syncing data to disk ... ok
mypostgres  | 
mypostgres  | 
mypostgres  | Success. You can now start the database server using:
mypostgres  | 
mypostgres  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
mypostgres  | 
mypostgres  | waiting for server to start....2024-03-10 16:41:31.879 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
mypostgres  | 2024-03-10 16:41:31.881 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mypostgres  | 2024-03-10 16:41:31.892 UTC [51] LOG:  database system was shut down at 2024-03-10 16:41:31 UTC
mypostgres  | 2024-03-10 16:41:31.898 UTC [48] LOG:  database system is ready to accept connections
mypostgres  |  done
mypostgres  | server started
mypostgres  | 
mypostgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
mypostgres  | CREATE DATABASE
mypostgres  | You are now connected to database "rinha" as user "postgres".
mypostgres  | CREATE TABLE
mypostgres  | CREATE TABLE
mypostgres  | INSERT 0 5
mypostgres  | 
mypostgres  | 
mypostgres  | waiting for server to shut down...2024-03-10 16:41:32.081 UTC [48] LOG:  received fast shutdown request
mypostgres  | .2024-03-10 16:41:32.084 UTC [48] LOG:  aborting any active transactions
mypostgres  | 2024-03-10 16:41:32.086 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
mypostgres  | 2024-03-10 16:41:32.086 UTC [49] LOG:  shutting down
mypostgres  | 2024-03-10 16:41:32.089 UTC [49] LOG:  checkpoint starting: shutdown immediate
mypostgres  | 2024-03-10 16:41:32.572 UTC [49] LOG:  checkpoint complete: wrote 938 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.392 s, sync=0.081 s, total=0.486 s; sync files=307, longest=0.054 s, average=0.001 s; distance=4291 kB, estimate=4291 kB; lsn=0/191B8E0, redo lsn=0/191B8E0
mypostgres  | 2024-03-10 16:41:32.578 UTC [48] LOG:  database system is shut down
mypostgres  |  done
mypostgres  | server stopped
mypostgres  | 
mypostgres  | PostgreSQL init process complete; ready for start up.
mypostgres  | 
mypostgres  | 2024-03-10 16:41:32.605 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
mypostgres  | 2024-03-10 16:41:32.605 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
mypostgres  | 2024-03-10 16:41:32.605 UTC [1] LOG:  listening on IPv6 address "::", port 5432
mypostgres  | 2024-03-10 16:41:32.610 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mypostgres  | 2024-03-10 16:41:32.618 UTC [65] LOG:  database system was shut down at 2024-03-10 16:41:32 UTC
mypostgres  | 2024-03-10 16:41:32.625 UTC [1] LOG:  database system is ready to accept connections
mynginx     | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
mynginx     | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
mynginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
mynginx     | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
mynginx     | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
mynginx     | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
mynginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
mynginx     | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
mynginx     | /docker-entrypoint.sh: Configuration complete; ready for start up
api2        | 
api2        | > rinha@1.0.0 start
api2        | > ts-node ./src/app.ts
api2        | 
api1        | 
api1        | > rinha@1.0.0 start
api1        | > ts-node ./src/app.ts
api1        | 
mynginx     | 2024/03/10 16:41:37 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:37 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:39 [error] 31#31: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:39 [error] 31#31: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:41 [error] 32#32: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:41 [error] 32#32: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:43 [error] 30#30: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:43 [error] 30#30: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:41:45 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api1        | Error connecting to the database Error: connect ECONNREFUSED 127.0.0.1:5432
api1        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1602:16) {
api1        |   errno: -111,
api1        |   code: 'ECONNREFUSED',
api1        |   syscall: 'connect',
api1        |   address: '127.0.0.1',
api1        |   port: 5432
api1        | }
api2        | Error connecting to the database Error: connect ECONNREFUSED 127.0.0.1:5432
api2        |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1602:16) {
api2        |   errno: -111,
api2        |   code: 'ECONNREFUSED',
api2        |   syscall: 'connect',
api2        |   address: '127.0.0.1',
api2        |   port: 5432
api2        | }
api1 exited with code 0
mynginx     | 2024/03/10 16:41:47 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api2 exited with code 0
mynginx     | 2024/03/10 16:42:24 [error] 29#29: *15 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:42 [error] 29#29: *15 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:47 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:47 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:49 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:51 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:56 [error] 29#29: *22 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:42:56 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:01 [error] 29#29: *24 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:01 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:03 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:05 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:10 [error] 29#29: *28 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:10 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:15 [error] 29#29: *30 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.3:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:15 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:17 [error] 29#29: *32 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:19 [error] 29#29: *33 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:24 [error] 29#29: *34 connect() failed (113: No route to host) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.18.0.4:3000/clientes/1/extrato", host: "localhost:9999"
mynginx     | 2024/03/10 16:43:24 [error] 29#29: *34 no live upstreams while connecting to upstream, client: 172.18.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
mynginx exited with code 0
mynginx exited with code 0
mypostgres  | 2024-03-10 16:43:27.553 UTC [1] LOG:  received fast shutdown request
mypostgres  | 2024-03-10 16:43:27.556 UTC [1] LOG:  aborting any active transactions
mypostgres  | 2024-03-10 16:43:27.558 UTC [1] LOG:  background worker "logical replication launcher" (PID 68) exited with exit code 1
mypostgres  | 2024-03-10 16:43:27.558 UTC [63] LOG:  shutting down
mypostgres  | 2024-03-10 16:43:27.561 UTC [63] LOG:  checkpoint starting: shutdown immediate
mypostgres  | 2024-03-10 16:43:27.598 UTC [63] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.016 s, total=0.041 s; sync files=13, longest=0.013 s, average=0.002 s; distance=261 kB, estimate=261 kB; lsn=0/195CCE0, redo lsn=0/195CCE0
mypostgres  | 2024-03-10 16:43:27.602 UTC [1] LOG:  database system is shut down
mypostgres exited with code 0
