 Container fraidev-db-1  Creating
 Container fraidev-db-1  Created
 Container fraidev-api02-1  Creating
 Container fraidev-api01-1  Creating
 Container fraidev-api02-1  Created
 Container fraidev-api01-1  Created
 Container fraidev-nginx-1  Creating
 Container fraidev-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-03-10 16:40:18.779 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-10 16:40:18.783 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-10 16:40:18.791 UTC [51] LOG:  database system was shut down at 2024-03-10 16:40:17 UTC
db-1     | 2024-03-10 16:40:18.803 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | SET
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | DO
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-03-10 16:40:19.013 UTC [48] LOG:  received fast shutdown request
db-1     | .2024-03-10 16:40:19.017 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-03-10 16:40:19.019 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-03-10 16:40:19.020 UTC [49] LOG:  shutting down
db-1     | 2024-03-10 16:40:19.022 UTC [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-10 16:40:19.532 UTC [49] LOG:  checkpoint complete: wrote 940 buffers (2.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.268 s, sync=0.230 s, total=0.513 s; sync files=315, longest=0.146 s, average=0.001 s; distance=4295 kB, estimate=4295 kB; lsn=0/191C9B0, redo lsn=0/191C9B0
db-1     | 2024-03-10 16:40:19.539 UTC [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-03-10 16:40:19.641 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-03-10 16:40:19.641 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-03-10 16:40:19.641 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-03-10 16:40:19.647 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-03-10 16:40:19.656 UTC [66] LOG:  database system was shut down at 2024-03-10 16:40:19 UTC
db-1     | 2024-03-10 16:40:19.663 UTC [1] LOG:  database system is ready to accept connections
api01-1  | thread 'main' panicked at src/main.rs:32:10:
api01-1  | can't connect to database: PoolTimedOut
api01-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
api02-1  | thread 'main' panicked at src/main.rs:32:10:
api02-1  | can't connect to database: PoolTimedOut
api02-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
api01-1 exited with code 101
api02-1 exited with code 101
nginx-1  | 2024/03/10 16:40:20 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:20 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:22 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:22 [error] 30#30: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:24 [error] 31#31: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:24 [error] 31#31: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:26 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:26 [error] 32#32: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:28 [error] 29#29: *13 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:30 [error] 29#29: *14 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:33 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:33 [error] 29#29: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:35 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:37 [error] 29#29: *19 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:39 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:41 [error] 29#29: *21 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:43 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:45 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:45 [error] 29#29: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:47 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:49 [error] 29#29: *27 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:51 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:53 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:55 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:57 [error] 29#29: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3002/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:57 [error] 29#29: *31 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://127.0.0.1:3001/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/03/10 16:40:59 [error] 29#29: *34 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-03-10 16:41:01.554 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-03-10 16:41:01.557 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-03-10 16:41:01.559 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-03-10 16:41:01.560 UTC [64] LOG:  shutting down
db-1     | 2024-03-10 16:41:01.562 UTC [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-03-10 16:41:01.604 UTC [64] LOG:  checkpoint complete: wrote 45 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.019 s, total=0.044 s; sync files=13, longest=0.016 s, average=0.002 s; distance=238 kB, estimate=238 kB; lsn=0/1958548, redo lsn=0/1958548
db-1     | 2024-03-10 16:41:01.608 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
