 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container rinha-pg  Creating
 Container rinha-pg  Created
 Container rizzo-nodejs-api03-1  Creating
 Container rizzo-nodejs-api01-1  Creating
 Container rizzo-nodejs-api02-1  Creating
 Container rizzo-nodejs-api03-1  Created
 Container rizzo-nodejs-api01-1  Created
 Container rizzo-nodejs-api02-1  Created
 Container rizzo-nodejs-nginx-1  Creating
 Container rizzo-nodejs-nginx-1  Created
Attaching to rinha-pg, api01-1, api02-1, api03-1, nginx-1
rinha-pg  | The files belonging to this database system will be owned by user "postgres".
rinha-pg  | This user must also own the server process.
rinha-pg  | 
rinha-pg  | The database cluster will be initialized with locale "en_US.utf8".
rinha-pg  | The default database encoding has accordingly been set to "UTF8".
rinha-pg  | The default text search configuration will be set to "english".
rinha-pg  | 
rinha-pg  | Data page checksums are disabled.
rinha-pg  | 
rinha-pg  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
rinha-pg  | creating subdirectories ... ok
rinha-pg  | selecting dynamic shared memory implementation ... posix
rinha-pg  | selecting default max_connections ... 100
rinha-pg  | selecting default shared_buffers ... 128MB
rinha-pg  | selecting default time zone ... Etc/UTC
rinha-pg  | creating configuration files ... ok
api01-1   | yarn run v1.22.19
api01-1   | $ prisma migrate deploy && prisma db seed
nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
rinha-pg  | running bootstrap script ... ok
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
api02-1   | yarn run v1.22.19
api03-1   | yarn run v1.22.19
api02-1   | $ prisma migrate deploy && prisma db seed
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
api03-1   | $ prisma migrate deploy && prisma db seed
api01-1   | Killed
api01-1   | error Command failed with exit code 137.
api01-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api02-1   | Killed
api02-1   | error Command failed with exit code 137.
api02-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
api03-1   | Killed
api03-1   | error Command failed with exit code 137.
api03-1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
rinha-pg  | performing post-bootstrap initialization ... ok
rinha-pg  | syncing data to disk ... ok
rinha-pg  | 
rinha-pg  | 
rinha-pg  | Success. You can now start the database server using:
rinha-pg  | 
rinha-pg  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
rinha-pg  | 
rinha-pg  | initdb: warning: enabling "trust" authentication for local connections
rinha-pg  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
rinha-pg  | waiting for server to start....2024-02-19 16:16:02.503 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-pg  | 2024-02-19 16:16:02.510 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-pg  | 2024-02-19 16:16:02.523 UTC [51] LOG:  database system was shut down at 2024-02-19 16:16:01 UTC
rinha-pg  | 2024-02-19 16:16:02.533 UTC [48] LOG:  database system is ready to accept connections
rinha-pg  |  done
rinha-pg  | server started
api01-1 exited with code 137
api03-1 exited with code 137
api02-1 exited with code 137
rinha-pg  | CREATE DATABASE
rinha-pg  | 
rinha-pg  | 
rinha-pg  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
rinha-pg  | 
rinha-pg  | waiting for server to shut down....2024-02-19 16:16:03.129 UTC [48] LOG:  received fast shutdown request
rinha-pg  | 2024-02-19 16:16:03.132 UTC [48] LOG:  aborting any active transactions
rinha-pg  | 2024-02-19 16:16:03.140 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
rinha-pg  | 2024-02-19 16:16:03.140 UTC [49] LOG:  shutting down
rinha-pg  | 2024-02-19 16:16:03.143 UTC [49] LOG:  checkpoint starting: shutdown immediate
rinha-pg  | 2024-02-19 16:16:03.627 UTC [49] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.401 s, sync=0.072 s, total=0.488 s; sync files=301, longest=0.053 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913070, redo lsn=0/1913070
rinha-pg  | 2024-02-19 16:16:03.632 UTC [48] LOG:  database system is shut down
rinha-pg  |  done
rinha-pg  | server stopped
rinha-pg  | 
rinha-pg  | PostgreSQL init process complete; ready for start up.
rinha-pg  | 
rinha-pg  | 2024-02-19 16:16:03.755 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
rinha-pg  | 2024-02-19 16:16:03.755 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rinha-pg  | 2024-02-19 16:16:03.755 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rinha-pg  | 2024-02-19 16:16:03.760 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rinha-pg  | 2024-02-19 16:16:03.767 UTC [64] LOG:  database system was shut down at 2024-02-19 16:16:03 UTC
rinha-pg  | 2024-02-19 16:16:03.815 UTC [1] LOG:  database system is ready to accept connections
nginx-1   | 2024/02/19 16:16:04 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:07 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:10 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:12 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:14 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:19 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:22 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:25 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:27 [error] 29#29: *11 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:29 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:34 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:38 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:41 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:43 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:48 [error] 29#29: *18 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:48 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:53 [error] 29#29: *20 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:56 [error] 29#29: *20 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:56 [error] 29#29: *20 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:16:58 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:03 [error] 29#29: *24 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:03 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:08 [error] 29#29: *26 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:11 [error] 29#29: *26 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:11 [error] 29#29: *26 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:13 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:18 [error] 29#29: *30 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:18 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:23 [error] 29#29: *32 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:26 [error] 29#29: *32 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:26 [error] 29#29: *32 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:28 [error] 29#29: *35 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:33 [error] 29#29: *36 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.3:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:33 [error] 29#29: *36 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:38 [error] 29#29: *38 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.4:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:41 [error] 29#29: *38 connect() failed (113: No route to host) while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://192.168.32.5:3000/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:41 [error] 29#29: *38 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/19 16:17:43 [error] 29#29: *41 no live upstreams while connecting to upstream, client: 192.168.32.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
rinha-pg  | 2024-02-19 16:17:46.728 UTC [1] LOG:  received fast shutdown request
rinha-pg  | 2024-02-19 16:17:46.731 UTC [1] LOG:  aborting any active transactions
rinha-pg  | 2024-02-19 16:17:46.733 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
rinha-pg  | 2024-02-19 16:17:46.734 UTC [62] LOG:  shutting down
rinha-pg  | 2024-02-19 16:17:46.737 UTC [62] LOG:  checkpoint starting: shutdown immediate
rinha-pg  | 2024-02-19 16:17:46.783 UTC [62] LOG:  checkpoint complete: wrote 34 buffers (0.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.023 s, total=0.050 s; sync files=11, longest=0.011 s, average=0.003 s; distance=159 kB, estimate=159 kB; lsn=0/193AC88, redo lsn=0/193AC88
rinha-pg  | 2024-02-19 16:17:46.787 UTC [1] LOG:  database system is shut down
rinha-pg exited with code 0
